config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Defines the root path route ("/")
  root "groups#index"

  resources :addresses
  resources :email_addresses
  resources :groups
  resources :phones
  resources :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/phone.rb
class Phone < ApplicationRecord
  validates :number,
    presence: true,
    uniqueness: true,
    length: { is: 10 },
    format: { with: /\A[0-9]+\z/ }

  has_many :links, foreign_key: "to_id", dependent: :destroy
  has_many :users, through: :links
  # has_many :groups, through: :links
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  allow_unauthenticated_access only: [ :index, :show, :new, :create, :edit, :update, :destroy ]
  before_action :set_resource, only: %i[ show edit update destroy ]

  # GET /phones or /phones.json
  def index
    @resources = Phone.all
  end

  # GET /phones/1 or /phones/1.json
  def show
  end

  # GET /phones/new
  def new
    @resource = Phone.new
  end

  # GET /phones/1/edit
  def edit
  end

  # POST /phones or /phones.json
  def create
    @resource = Phone.new(resource_params)

    respond_to do |format|
      if @resource.save
        format.html { redirect_to @resource, notice: "Phone was successfully created." }
        format.json { render :show, status: :created, location: @resource }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phones/1 or /phones/1.json
  def update
    respond_to do |format|
      if @resource.update(resource_params)
        format.html { redirect_to @resource, notice: "Phone was successfully updated." }
        format.json { render :show, status: :ok, location: @resource }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1 or /phones/1.json
  def destroy
    @resource.destroy!

    respond_to do |format|
      format.html { redirect_to phones_path, status: :see_other, notice: "Phone was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @resource = Phone.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def resource_params
      params.expect(phone: [ :number ])
    end
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/phones/_form.html.haml
= form_with(model: phone) do |form|
  - if phone.errors.any?
    .error-messages{ style: "color: red" }
      %h2= "#{pluralize(phone.errors.count, 'error')} prohibited this phone from being saved:"
      %ul
        - phone.errors.each do |error|
          %li= error.full_message

  .form-group
    = form.label :number, style: "display: block"
    = form.text_field :number

  .form-group
    = form.submit

app/views/phones/_phone.html.haml
%div{ id: dom_id(phone) }
  %p
    %strong Number:
    = phone.number

app/views/phones/edit.html.haml
- content_for :title, "Editing phone"

%h1 Editing phone

= render "form", phone: @resource

%br

%div
  = link_to "Show this phone", @resource
  |
  = link_to "Back to phones", phones_path

app/views/phones/index.html.haml
%p{ style: "color: green" }= notice

- content_for :title, "Phones"

%h1 Phones

#phones
  - @resources.each do |phone|
    = render phone
    %p
      = link_to "Show this phone", phone

= link_to "New phone", new_phone_path

app/views/phones/new.html.haml
- content_for :title, "New phone"

%h1 New phone

= render "form", phone: @resource

%br/

%div
  = link_to "Back to phones", phones_path

app/views/phones/show.html.haml
%p{ style: "color: green" }= notice

= render @resource

%div
  = link_to "Edit this phone", edit_phone_path(@resource)
  |
  = link_to "Back to phones", phones_path
  = button_to "Destroy this phone", @resource, method: :delete