config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Defines the root path route ("/")
  root "groups#index"

  resources :addresses
  resources :email_addresses
  resources :groups
  resources :phones
  resources :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true

  has_many :links, dependent: :destroy
  has_many :phones, through: :links
  # has_many :email_addresses, through: :links, source: :from, source_type: "EmailAddress"
  # has_many :addresses, through: :links, source: :from, source_type: "Address"
  #
  has_many :roles, dependent: :destroy
  has_many :users, through: :roles
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  include ResourcesController

  # allow_unauthenticated_access only:
  #   [ :index, :show, :new, :create, :edit, :update, :destroy ]

  private
    def resource_params
      params.expect(group:
        [ :name, :description ])
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= form_with(model: group) do |form|
  - if group.errors.any?
    .error-messages{ style: "color: red" }
      %h2= "#{pluralize(group.errors.count, 'error')} prohibited this group from being saved:"
      %ul
        - group.errors.each do |error|
          %li= error.full_message

  .form-group
    = form.label :name, style: "display: block"
    = form.text_field :name

  .form-group
    = form.label :description, style: "display: block"
    = form.textarea :description

  .form-group
    = form.submit

app/views/groups/_group.html.haml
%div{ id: dom_id(group) }
  %p
    %strong Name:
    = group.name

  %p
    %strong Description:
    = group.description

app/views/groups/edit.html.haml
- content_for :title, "Editing group"

%h1 Editing group

= render "form", group: @resource

%br/

%div
  = link_to "Show this group", @resource
  |
  = link_to "Back to groups", groups_path

app/views/groups/index.html.haml
%p{ style: "color: green" }= notice

- content_for :title, "Groups"

%h1 Groups

#groups
  - @resources.each do |group|
    = render group
    %p
      = link_to "Show this group", group

= link_to "New group", new_group_path

app/views/groups/new.html.haml
- content_for :title, "New group"

%h1 New group

= render "form", group: @resource

%br/

%div
  = link_to "Back to groups", groups_path

app/views/groups/show.html.haml
%p{ style: "color: green" }= notice

%h1 Group
= render @resource

%div
  = link_to "Edit this group", edit_group_path(@resource)
  |
  = link_to "Back to groups", groups_path
  = button_to "Destroy this group", @resource, method: :delete

%h1 Group's Users
- @resource.users.each do |user|
  %div
    = link_to user.email, user_path(user)
    
%h1 Group's Phone Numbers
-# @resource.phones.each do |phone|
  %div
    = link_to phone.number, phone_path(phone)

%h1 Group's Email Addresses
-# @resource.email_addresses.each do |email_address|
  %div
  = link_to email_address.address, email_address_path(email_address)

%h3 Group's Addresses
-# @resource.addresses.each do |address|
  %div
  = link_to address.street1, email_address_path(address)