config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Defines the root path route ("/")
  root "groups#index"

  resources :addresses
  resources :email_addresses
  resources :groups
  resources :phones
  resources :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/email_address.rb
class EmailAddress < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true

  has_many :links, dependent: :destroy
  has_many :phones, through: :links
  # has_many :email_addresses, through: :links, source: :from, source_type: "EmailAddress"
  # has_many :addresses, through: :links, source: :from, source_type: "Address"
  #
  has_many :roles, dependent: :destroy
  has_many :users, through: :roles
end

app/models/link.rb
class Link < ApplicationRecord
  # From user or group
  belongs_to :user, foreign_key: "from_id"

  # to phone, email_address, or address
  belongs_to :phone, foreign_key: "to_id"
  belongs_to :email_address, foreign_key: "to_id"
  belongs_to :address, foreign_key: "to_id"

  belongs_to :from, polymorphic: true
  belongs_to :to, polymorphic: true
end

app/models/phone.rb
class Phone < ApplicationRecord
  validates :number,
    presence: true,
    uniqueness: true,
    length: { is: 10 },
    format: { with: /\A[0-9]+\z/ }

  has_many :links, foreign_key: "to_id", dependent: :destroy
  has_many :users, through: :links
  # has_many :groups, through: :links
end

app/models/role.rb
class Role < ApplicationRecord
  STATUSES=%w[active inactive]
  KINDS=%w[member admin user]

  belongs_to :user
  belongs_to :group

  validates :user_id, presence: true, uniqueness: { scope: :group_id }
  validates :group_id, presence: true
  validates :kind, presence: true, inclusion: { in: KINDS }
  validates :status, presence: true, inclusion: { in: STATUSES }
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :roles
  has_many :groups, through: :roles

  has_many :links, as: :from, dependent: :destroy
  has_many :phones, through: :links
  has_many :email_addresses, through: :links
  has_many :addresses, through: :links
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  include ResourcesController

  allow_unauthenticated_access only:
    [ :index, :show, :new, :create, :edit, :update, :destroy ]

  private

  def resource_params
    params.expect(address:
      [ :street1, :street2, :city, :state, :country, :zipcode ])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Check if there is a before_action that requires authentication
  # before_action :authenticate_user! # This might be causing the redirection
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_user_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/email_addresses_controller.rb
class EmailAddressesController < ApplicationController
  include ResourcesController

  allow_unauthenticated_access only:
    [ :index, :show, :new, :create, :edit, :update, :destroy ]

  private

  def resource_params
    params.expect(email_address:
      [ :address, :kind, :status ])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  include ResourcesController

  # allow_unauthenticated_access only:
  #   [ :index, :show, :new, :create, :edit, :update, :destroy ]

  private
    def resource_params
      params.expect(group:
        [ :name, :description ])
    end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  allow_unauthenticated_access only: [ :index, :show, :new, :create, :edit, :update, :destroy ]
  before_action :set_resource, only: %i[ show edit update destroy ]

  # GET /phones or /phones.json
  def index
    @resources = Phone.all
  end

  # GET /phones/1 or /phones/1.json
  def show
  end

  # GET /phones/new
  def new
    @resource = Phone.new
  end

  # GET /phones/1/edit
  def edit
  end

  # POST /phones or /phones.json
  def create
    @resource = Phone.new(resource_params)

    respond_to do |format|
      if @resource.save
        format.html { redirect_to @resource, notice: "Phone was successfully created." }
        format.json { render :show, status: :created, location: @resource }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phones/1 or /phones/1.json
  def update
    respond_to do |format|
      if @resource.update(resource_params)
        format.html { redirect_to @resource, notice: "Phone was successfully updated." }
        format.json { render :show, status: :ok, location: @resource }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1 or /phones/1.json
  def destroy
    @resource.destroy!

    respond_to do |format|
      format.html { redirect_to phones_path, status: :see_other, notice: "Phone was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @resource = Phone.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def resource_params
      params.expect(phone: [ :number ])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ResourcesController

  # allow_unauthenticated_access only:
  #   [ :index, :show, :new, :create, :edit, :update, :destroy ]

  private

  def resource_params
    params.expect(user:
      [ :email, :password, :password_confirmation ])
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_addresses_helper.rb
module EmailAddressesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/addresses/_address.html.haml
%div{ id: dom_id(address) }
  %p
    %strong Street1:
    = address.street1

  %p
    %strong Street2:
    = address.street2

  %p
    %strong City:
    = address.city

  %p
    %strong State:
    = address.state

  %p
    %strong Country:
    = address.country

  %p
    %strong Zipcode:
    = address.zipcode

app/views/addresses/_form.html.haml
= form_with(model: address) do |form|
  - if address.errors.any?
    .error-messages{ style: "color: red" }
      %h2= pluralize(address.errors.count, "error") + " prohibited this address from being saved:"
      %ul
        - address.errors.each do |error|
          %li= error.full_message

  .form-group
    = form.label :street1, style: "display: block"
    = form.text_field :street1

  .form-group
    = form.label :street2, style: "display: block"
    = form.text_field :street2

  .form-group
    = form.label :city, style: "display: block"
    = form.text_field :city

  .form-group
    = form.label :state, style: "display: block"
    = form.text_field :state

  .form-group
    = form.label :country, style: "display: block"
    = form.text_field :country

  .form-group
    = form.label :zipcode, style: "display: block"
    = form.text_field :zipcode

  .form-group
    = form.submit

app/views/addresses/edit.html.haml
- content_for :title, "Editing address"

%h1 Editing address

= render "form", address: @resource

%br/

%div
  = link_to "Show this address", @resource
  |
  = link_to "Back to addresses", addresses_path

app/views/addresses/index.html.haml
%p{ style: "color: green" }= notice

- content_for :title, "Addresses"

%h1 Addresses

#addresses
  - @resources.each do |address|
    = render address
    %p
      = link_to "Show this address", address

= link_to "New address", new_address_path

app/views/addresses/new.html.haml
- content_for :title, "New address"

%h1 New address

= render "form", address: @resource

%br/

%div
  = link_to "Back to addresses", addresses_path

app/views/addresses/show.html.haml
%p{ style: "color: green" }= notice

= render @resource

%div
  = link_to "Edit this address", edit_address_path(@resource)
  |
  = link_to "Back to addresses", addresses_path

  = button_to "Destroy this address", @resource, method: :delete

app/views/email_addresses/_email_address.html.haml
%div{ id: dom_id(email_address) }
  %p
    %strong Address:
    = email_address.address

  %p
    %strong Kind:
    = email_address.kind

  %p
    %strong Status:
    = email_address.status

app/views/email_addresses/_form.html.haml
= form_with(model: email_address) do |form|
  - if email_address.errors.any?
    .error-messages{ style: "color: red" }
      %h2= "#{pluralize(email_address.errors.count, 'error')} prohibited this email_address from being saved:"
      %ul
        - email_address.errors.each do |error|
          %li= error.full_message

  .form-group
    = form.label :address, style: "display: block"
    = form.text_field :address

  .form-group
    = form.label :kind, style: "display: block"
    = form.text_field :kind

  .form-group
    = form.label :status, style: "display: block"
    = form.text_field :status

  .form-group
    = form.submit

app/views/email_addresses/edit.html.haml
- content_for :title, "Editing email address"

%h1 Editing email address

= render "form", email_address: @resource

%br/

%div
  = link_to "Show this email address", @resource
  |
  = link_to "Back to email addresses", email_addresses_path

app/views/email_addresses/index.html.haml
%p{ style: "color: green" }= notice

- content_for :title, "Email addresses"

%h1 Email addresses

#email_addresses
  - @resources.each do |email_address|
    = render email_address
    %p
      = link_to "Show this email address", email_address

= link_to "New email address", new_email_address_path

app/views/email_addresses/new.html.haml
- content_for :title, "New email address"

%h1 New email address

= render "form", email_address: @resource

%br/

%div
  = link_to "Back to email addresses", email_addresses_path

app/views/email_addresses/show.html.haml
%p{ style: "color: green" }= notice

= render @resource

%div
  = link_to "Edit this email address", edit_email_address_path(@resource)
  |
  = link_to "Back to email addresses", email_addresses_path

  = button_to "Destroy this email address", @resource, method: :delete

app/views/users/_form.html.haml
= form_with(model: user) do |form|
  - if user.errors.any?
    .error-messages{ style: "color: red" }
      %h2= "#{pluralize(user.errors.count, 'error')} prohibited this user from being saved:"
      %ul
        - user.errors.each do |error|
          %li= error.full_message

  .field
    = form.label :email, style: "display: block"
    = form.text_field :email_address

  .field
    = form.label :password, style: "display: block"
    = form.password_field :password

  .field
    = form.label :password_confirmation, style: "display: block"
    = form.password_field :password_confirmation

  .actions
    = form.submit

app/views/users/_user.html.haml
%div{ id: dom_id(user) }
  %p
    %strong Email:
    = user.email

app/views/users/edit.html.haml
- content_for :title, "Editing user"

%h1 Editing User

= render "form", user: @resource

%br

%div
  = link_to "Show this user", @resource
  |
  = link_to "Back to users", users_path
 

app/views/users/index.html.haml
%p{ style: "color: green" }= notice

- content_for :title, "Users"

%h1 Users

#users
  - @resources.each do |user|
    = render user
    %p
      = link_to "Show this user", user

= link_to "New user", new_user_path

app/views/users/new.html.haml
- content_for :title, "New user"

%h1 New User

= render "form", user: @resource

%br

%div
  = link_to "Back to users", users_path

app/views/users/show.html.haml
%p{ style: "color: green" }= notice

%h1 User
= render @resource

%div
  = link_to "Edit this user", edit_user_path(@resource)
  |
  = link_to "Back to users", users_path
  = button_to "Destroy this user", @resource, method: :delete

%h1 User's Groups
- @resource.groups.each do |group|
  %div
    = link_to group.name, group_path(group)

%h1 User's Phone Numbers
- @resource.phones.each do |phone|
  %div
    = link_to phone.number, phone_path(phone)

%h1 User's Email addresses
- @resource.email_addresses.each do |email_address|
  %div
  = link_to email_address.address, email_address_path(email_address)

%h1 User's Addresses
- @resource.addresses.each do |address|
  %div
  = link_to address.street1, email_address_path(address)